name: CI Pipeline to destroy Infrastructure

on:
  workflow_dispatch: 
jobs:
    build:
      runs-on: ubuntu-latest
      environment: dev
      steps:
        - name: Checkout repository
          uses: actions/checkout@v2

        - name: Setup environment variables 
          working-directory: environments/dev
          run: |
            echo "setting up env variables"
            echo "ARM_SUBSCRIPTION_ID=${{secrets.SUBSCRIPTION_ID}}" >> $GITHUB_ENV
            echo "ARM_TENANT_ID=${{secrets.TENANTID}}" >> $GITHUB_ENV
            echo "ARM_CLIENT_ID=${{secrets.CLIENT_ID}}" >> $GITHUB_ENV
            echo "ARM_CLIENT_SECRET=${{secrets.CLIENT_SECRET}}" >> $GITHUB_ENV
            echo "TF_VAR_subscription_id=${{secrets.SUBSCRIPTION_ID}}" >> $GITHUB_ENV
            
        - name: Setup Terraform
          uses: hashicorp/setup-terraform@v1
         
        - name: Terraform Init
          working-directory: environments/dev
          run: terraform init

        - name: Terraform Validate Distruction
          working-directory: environments/dev
          run: terraform validate

        - name: Terraform Plan Distruction 
          working-directory: environments/dev
          run: terraform plan -destroy -out main.dev.destroy.tfplan 
          env:
            TF_VAR_domain: ${{secrets.DOMAIN}}
            TF_VAR_github_token: ${{secrets.GITHUBTOKEN}}
            TF_VAR_github_owner: ${{secrets.GITHUBOWNER}}
            TF_VAR_arm_client_id: ${{secrets.CLIENT_ID}}
            TF_VAR_subscription_id: ${{secrets.SUBSCRIPTION_ID}}
            TF_VAR_arm_client_secret: ${{secrets.CLIENT_SECRET}}
            TF_VAR_arm_tenant_id: ${{secrets.TENANTID}}
            TF_VAR_resource_group_prefix: ${{secrets.RESOURCEGROUPPREFIX}}
            TF_VAR_tla: ${{secrets.TLA}}
            TF_VAR_location_suffix: ${{secrets.LOCATIONSUFFIX}}
            TF_VAR_rg_location: ${{secrets.RGLOCATION}}
            TF_VAR_github_environment: ${{secrets.ENVIRONMENT}} 

        - name: Terraform Apply Distruction
          working-directory: environments/dev
          run: terraform apply main.dev.destroy.tfplan

    